[package]
name = "rust_small_projs"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
plotters = "0.3"
regex = "1.7"
serde_json = "1.0"
serde = { version="1.0", features = ["derive"]}
dioxus = {version="0.5", features=["desktop"]}
dioxus-desktop="0.5"
nalgebra = "0.33.2"
